// <auto-generated />
namespace Capstoneproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedcommentmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedcommentmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201807312231474_updated comment model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
